apiVersion: v2
name: moda
description: MODA Signal Processing Toolkit
type: application
version: 0.1.0
appVersion: "2.0.0"
kubeVersion: ">=1.20.0"

keywords:
  - signal-processing
  - matlab

home: https://github.com/st7ma784/MODA
sources:
  - https://github.com/st7ma784/MODA

maintainers:
  - name: MODA Team

dependencies: []
