{{- if .Values.fastmoda.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "moda.fullname" . }}-fastmoda
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "moda.labels" . | nindent 4 }}
    app.kubernetes.io/component: fastmoda
    app.kubernetes.io/port: {{ .Values.fastmoda.service.port | quote }}
  {{- with .Values.fastmoda.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.fastmoda.service.type }}
  ports:
    - port: {{ .Values.fastmoda.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "moda.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: fastmoda
{{- end }}

---
{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "moda.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "moda.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "moda.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}

---
{{- if .Values.server.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "moda.fullname" . }}-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "moda.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
    app.kubernetes.io/port: {{ .Values.server.service.port | quote }}
  {{- with .Values.server.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: matlab
      protocol: TCP
      name: matlab
  selector:
    {{- include "moda.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
{{- end }}

---
{{- if .Values.mobile.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "moda.fullname" . }}-mobile
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "moda.labels" . | nindent 4 }}
    app.kubernetes.io/component: mobile
    app.kubernetes.io/port: {{ .Values.mobile.service.port | quote }}
  {{- with .Values.mobile.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.mobile.service.type }}
  ports:
    - port: {{ .Values.mobile.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "moda.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mobile
{{- end }}

---
{{- if .Values.signal.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "moda.fullname" . }}-signal
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "moda.labels" . | nindent 4 }}
    app.kubernetes.io/component: signal
    app.kubernetes.io/port: {{ .Values.signal.service.port | quote }}
  {{- with .Values.signal.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.signal.service.type }}
  ports:
    - port: {{ .Values.signal.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "moda.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: signal
{{- end }}

---
{{- if .Values.emulator.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "moda.fullname" . }}-emulator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "moda.labels" . | nindent 4 }}
    app.kubernetes.io/component: emulator
    app.kubernetes.io/port: {{ .Values.emulator.service.port | quote }}
  {{- with .Values.emulator.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.emulator.service.type }}
  ports:
    - port: {{ .Values.emulator.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "moda.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: emulator
{{- end }}
